# Use Travis container-based infrastructure
sudo: false

# Elixir baby!
language: 'elixir'

elixir: 1.8.1
otp_release: 21.2.5
node_js: 9.5.0

cache:
  directories:
  - _build
  - deps
  - webapp/node_modules

# Make sure PostgreSQL is running
addons:
  postgresql: 9.6
  apt:
    packages:
      - libyaml-dev

# Set global environment variables
env:
  global:
    - NODE_VERSION: '9.5.0'
    - MIX_ENV: 'test'
    - SECRET_KEY_BASE: 'lolwut'
    - DATABASE_URL: 'postgres://localhost/accent_web_test'

# Output Travis server IP for debugging
before_install:
  - 'echo `curl --verbose http://jsonip.com`'
  - npm config set spin false
  - npm ci --prefix webapp --no-audit --no-color
  - npm ci --prefix cli --no-audit --no-color
  - npm ci --prefix jipt --no-audit --no-color
  - npm --prefix webapp run build-production

# Create database and prepare the application
before_script:
  - mix compile
  - mix ecto.setup

script:
  - ./priv/script/ci-check.sh
  - npm --prefix cli run build
  - npm --prefix jipt run build-production
  - mix coveralls.travis
