# Default values for accent-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: andreymaznyak/accent
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - accent.apps.example.com
  tls:
    - secretName: example-translate-tls-cert
      hosts:
      - accent.apps.example.com

service:
  type: ClusterIP
  port: 4000

# Default config values
API_HOST: https://accent.apps.example.com
API_WS_HOST: wss://accent.apps.example.com
CANONICAL_HOST: accent.apps.example.com
DATABASE_URL: postgres://postgres:password@example.com/accent
GOOGLE_API_CLIENT_ID: example.com
MAILER_FROM: noreply@example.com
MIX_ENV: prod
PORT: "4000"
RESTRICTED_DOMAIN: example.com
SENTRY_DSN: https://12345678@sentry.io/12345678
SMTP_ADDRESS: smtp.sendgrid.net
SMTP_PASSWORD: PASSWORDPASSWORD
SMTP_PORT: "587"
SMTP_USERNAME: apikey
WEBAPP_EMAIL_HOST: chibifire.com
WEBAPP_SENTRY_DSN: https://12345678@sentry.io/12345678